package Interfaces;

import Implementaciones.PacienteImplementacion;
import Modelos.Paciente;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author edwin-993
 */
public class InterfazPaciente extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPaciente
     */
    public InterfazPaciente() throws Exception {
        this.setLocationRelativeTo(null);
        initComponents();
        listarRegistros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cmbOrden = new javax.swing.JComboBox<>();
        txtCriterio = new javax.swing.JTextField();
        tbdFunciones = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtEdad = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtNSS = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtEdad2 = new javax.swing.JTextField();
        txtApellidoPaterno2 = new javax.swing.JTextField();
        txtNSS2 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtAltura2 = new javax.swing.JTextField();
        txtId2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtApellidoMaterno2 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBorrar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtEdad1 = new javax.swing.JTextField();
        txtApellidoPaterno1 = new javax.swing.JTextField();
        txtNSS1 = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtAltura1 = new javax.swing.JTextField();
        txtId1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtApellidoMaterno1 = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnBorrar1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Paciente");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros recientes (40)"));

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistros);

        jLabel22.setText("Filtrar mediante:");

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Identificador", "Numero de seguro social", "Nombre", "Altura" }));
        cmbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltroActionPerformed(evt);
            }
        });

        jLabel23.setText("Con orden:");

        cmbOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));
        cmbOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenActionPerformed(evt);
            }
        });

        txtCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCriterioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCriterio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdFuncionesMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del paciente"));

        txtEdad.setText("Ingrese la edad");
        txtEdad.setMaximumSize(new java.awt.Dimension(201, 24));
        txtEdad.setMinimumSize(new java.awt.Dimension(201, 24));
        txtEdad.setPreferredSize(new java.awt.Dimension(201, 24));
        txtEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEdadFocusGained(evt);
            }
        });

        txtApellidoPaterno.setText("Ingrese el apellido paterno");
        txtApellidoPaterno.setMaximumSize(new java.awt.Dimension(201, 24));
        txtApellidoPaterno.setMinimumSize(new java.awt.Dimension(201, 24));
        txtApellidoPaterno.setPreferredSize(new java.awt.Dimension(201, 24));
        txtApellidoPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoPaternoFocusGained(evt);
            }
        });

        txtNSS.setText("Ingrese NSS");
        txtNSS.setMaximumSize(new java.awt.Dimension(201, 24));
        txtNSS.setMinimumSize(new java.awt.Dimension(201, 24));
        txtNSS.setPreferredSize(new java.awt.Dimension(201, 24));
        txtNSS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNSSFocusGained(evt);
            }
        });

        txtNombre.setText("Ingrese 1 nombre");
        txtNombre.setMaximumSize(new java.awt.Dimension(201, 24));
        txtNombre.setMinimumSize(new java.awt.Dimension(201, 24));
        txtNombre.setPreferredSize(new java.awt.Dimension(201, 24));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
        });

        txtAltura.setText("Ingrese la altura");
        txtAltura.setMaximumSize(new java.awt.Dimension(201, 24));
        txtAltura.setMinimumSize(new java.awt.Dimension(201, 24));
        txtAltura.setPreferredSize(new java.awt.Dimension(201, 24));
        txtAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAlturaFocusGained(evt);
            }
        });

        txtId.setText("Cargar id nuevo");
        txtId.setEnabled(false);
        txtId.setMaximumSize(new java.awt.Dimension(201, 24));
        txtId.setMinimumSize(new java.awt.Dimension(201, 24));
        txtId.setPreferredSize(new java.awt.Dimension(201, 24));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Apellido paterno:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Edad:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Numero de seguro social:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Altura en metros:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Apellido materno:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Nombre:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Identificador:");

        txtApellidoMaterno.setText("Ingrese el apellido paterno");
        txtApellidoMaterno.setMaximumSize(new java.awt.Dimension(201, 24));
        txtApellidoMaterno.setMinimumSize(new java.awt.Dimension(201, 24));
        txtApellidoMaterno.setPreferredSize(new java.awt.Dimension(201, 24));
        txtApellidoMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoMaternoFocusGained(evt);
            }
        });

        btnRegistrar.setText("Registrar paciente");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar y cancelar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAltura, txtApellidoMaterno, txtApellidoPaterno, txtEdad, txtId, txtNSS, txtNombre});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBorrar))
                .addContainerGap())
        );

        tbdFunciones.addTab("Insertar", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del paciente"));

        txtEdad2.setText("Ingrese la edad");
        txtEdad2.setEnabled(false);
        txtEdad2.setMaximumSize(new java.awt.Dimension(201, 24));
        txtEdad2.setMinimumSize(new java.awt.Dimension(201, 24));
        txtEdad2.setPreferredSize(new java.awt.Dimension(201, 24));

        txtApellidoPaterno2.setText("Ingrese el apellido paterno");
        txtApellidoPaterno2.setEnabled(false);
        txtApellidoPaterno2.setMaximumSize(new java.awt.Dimension(201, 24));
        txtApellidoPaterno2.setMinimumSize(new java.awt.Dimension(201, 24));
        txtApellidoPaterno2.setPreferredSize(new java.awt.Dimension(201, 24));

        txtNSS2.setText("Ingrese NSS");
        txtNSS2.setEnabled(false);
        txtNSS2.setMaximumSize(new java.awt.Dimension(201, 24));
        txtNSS2.setMinimumSize(new java.awt.Dimension(201, 24));
        txtNSS2.setPreferredSize(new java.awt.Dimension(201, 24));

        txtNombre2.setText("Ingrese 1 nombre");
        txtNombre2.setEnabled(false);
        txtNombre2.setMaximumSize(new java.awt.Dimension(201, 24));
        txtNombre2.setMinimumSize(new java.awt.Dimension(201, 24));
        txtNombre2.setPreferredSize(new java.awt.Dimension(201, 24));

        txtAltura2.setText("Ingrese altura");
        txtAltura2.setEnabled(false);
        txtAltura2.setMaximumSize(new java.awt.Dimension(201, 24));
        txtAltura2.setMinimumSize(new java.awt.Dimension(201, 24));
        txtAltura2.setPreferredSize(new java.awt.Dimension(201, 24));

        txtId2.setText("Cargar id nuevo");
        txtId2.setEnabled(false);
        txtId2.setMaximumSize(new java.awt.Dimension(201, 24));
        txtId2.setMinimumSize(new java.awt.Dimension(201, 24));
        txtId2.setPreferredSize(new java.awt.Dimension(201, 24));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Apellido paterno:");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Edad:");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Numero de seguro social:");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Altura en metros:");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Apellido materno:");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Nombre:");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Identificador:");

        txtApellidoMaterno2.setText("Ingrese el apellido paterno");
        txtApellidoMaterno2.setEnabled(false);
        txtApellidoMaterno2.setMaximumSize(new java.awt.Dimension(201, 24));
        txtApellidoMaterno2.setMinimumSize(new java.awt.Dimension(201, 24));
        txtApellidoMaterno2.setPreferredSize(new java.awt.Dimension(201, 24));

        btnGuardar.setText("Guardar cambios");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar2.setText("Borrar y cancelar");
        btnBorrar2.setEnabled(false);
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApellidoPaterno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApellidoMaterno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEdad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAltura2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNSS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar2)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel20, jLabel21});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAltura2, txtApellidoMaterno2, txtApellidoPaterno2, txtEdad2, txtNSS2, txtNombre2});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtApellidoPaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtApellidoMaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtAltura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNSS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBorrar2))
                .addContainerGap())
        );

        tbdFunciones.addTab("Editar", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del paciente"));

        txtEdad1.setText("Ingrese la edad");
        txtEdad1.setEnabled(false);
        txtEdad1.setMaximumSize(new java.awt.Dimension(201, 24));
        txtEdad1.setMinimumSize(new java.awt.Dimension(201, 24));
        txtEdad1.setPreferredSize(new java.awt.Dimension(201, 24));

        txtApellidoPaterno1.setText("Ingrese el apellido paterno");
        txtApellidoPaterno1.setEnabled(false);
        txtApellidoPaterno1.setMaximumSize(new java.awt.Dimension(201, 24));
        txtApellidoPaterno1.setMinimumSize(new java.awt.Dimension(201, 24));
        txtApellidoPaterno1.setPreferredSize(new java.awt.Dimension(201, 24));

        txtNSS1.setText("Ingrese NSS");
        txtNSS1.setEnabled(false);
        txtNSS1.setMaximumSize(new java.awt.Dimension(201, 24));
        txtNSS1.setMinimumSize(new java.awt.Dimension(201, 24));
        txtNSS1.setPreferredSize(new java.awt.Dimension(201, 24));

        txtNombre1.setText("Ingrese 1 nombre");
        txtNombre1.setEnabled(false);
        txtNombre1.setMaximumSize(new java.awt.Dimension(201, 24));
        txtNombre1.setMinimumSize(new java.awt.Dimension(201, 24));
        txtNombre1.setPreferredSize(new java.awt.Dimension(201, 24));

        txtAltura1.setText("Ingrese altura");
        txtAltura1.setEnabled(false);
        txtAltura1.setMaximumSize(new java.awt.Dimension(201, 24));
        txtAltura1.setMinimumSize(new java.awt.Dimension(201, 24));
        txtAltura1.setPreferredSize(new java.awt.Dimension(201, 24));

        txtId1.setText("Cargar id nuevo");
        txtId1.setEnabled(false);
        txtId1.setMaximumSize(new java.awt.Dimension(201, 24));
        txtId1.setMinimumSize(new java.awt.Dimension(201, 24));
        txtId1.setPreferredSize(new java.awt.Dimension(201, 24));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Apellido paterno:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Edad:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Numero de seguro social:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Altura en metros:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Apellido materno:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nombre:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Identificador:");

        txtApellidoMaterno1.setText("Ingrese el apellido paterno");
        txtApellidoMaterno1.setEnabled(false);
        txtApellidoMaterno1.setMaximumSize(new java.awt.Dimension(201, 24));
        txtApellidoMaterno1.setMinimumSize(new java.awt.Dimension(201, 24));
        txtApellidoMaterno1.setPreferredSize(new java.awt.Dimension(201, 24));

        btnEliminar.setText("Eliminar paciente");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBorrar1.setText("Borrar y cancelar");
        btnBorrar1.setEnabled(false);
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoMaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNSS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar1)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel8, jLabel9});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAltura1, txtApellidoMaterno1, txtApellidoPaterno1, txtEdad1, txtId1, txtNSS1, txtNombre1});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtApellidoPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtApellidoMaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNSS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnBorrar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdFunciones.addTab("Eliminar", jPanel3);

        btnRegresar.setText("Regresar al menú principal");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tbdFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbdFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroActionPerformed
        try {
            // TODO add your handling code here:
            listarRegistros();
        } catch (Exception ex) {
            Logger.getLogger(InterfazPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbFiltroActionPerformed

    private void cmbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenActionPerformed
        try {
            // TODO add your handling code here:
            listarRegistros();
        } catch (Exception ex) {
            Logger.getLogger(InterfazPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbOrdenActionPerformed

    private void txtCriterioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioKeyReleased
        try {
            // TODO add your handling code here:
            listarRegistros();
        } catch (Exception ex) {
            Logger.getLogger(InterfazPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCriterioKeyReleased

    private void tbdFuncionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdFuncionesMouseClicked
        //tablaSeleccionada se vuelve true cuando se encuentra seleccionada una fila en la tabla
        boolean tablaSeleccionada = tblRegistros.getSelectedRow() != -1;
        System.out.println(tablaSeleccionada); //Mensaje de bandera
        //tabSeleccionada se obtiene mediante el metodo getSelectedIndex, por lo que puede
        //tener valores de 0 a 2, 0 = insertar, 1 = editar, 2 = eliminar
        int tabSeleccionada = tbdFunciones.getSelectedIndex(); //Mensaje de bandera
        System.out.println(tabSeleccionada);//Mensaje de bandera
        //En caso de que la tab sea 1 o 2 y que se encuentre seleccionado un registro

        if (JOptionPane.showConfirmDialog(rootPane, """
                                                   Al cambiar de funcion se perderan los cambios de la funcion actual
                                                   Esta usted seguro de querer proceder?""", "Confirmación de eliminacion",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if ((tabSeleccionada == 1 || tabSeleccionada == 2) && tablaSeleccionada) {
                //Se activa la tab correspondiente segun la seleccion del usuario mediante un switch
                switch (tabSeleccionada) {
                    case 1 -> {
                        editar(true);
                        eliminar(false);
                        insertar(false);
                        btnRegresar.setEnabled(false);
                    }
                    case 2 -> {
                        eliminar(true);
                        editar(false);
                        insertar(false);
                        btnRegresar.setEnabled(false);
                    }
                    default ->
                        System.out.println("Ocurrio un error inesperado, favor de contactar al desarrollador");
                }
            } else {
                //De lo contrario, se regresa el indice a 0, insersion
                tbdFunciones.setSelectedIndex(0);
                insertar(true);
                eliminar(false);
                editar(false);
                btnRegresar.setEnabled(true);
                limpiarInsertar();
                limpiarEliminar();
            }
        }

    }//GEN-LAST:event_tbdFuncionesMouseClicked

    private void tblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosMouseClicked
        // TODO add your handling code here:
        tbdFunciones.setSelectedIndex(1);
        editar(true);
        insertar(false);
        eliminar(true);
        int fila = tblRegistros.getSelectedRow();
        ArrayList<String> nombreSeparado;

        //SE RECUPERAN LOS DATOS EN EDITAR
        txtId2.setText(tblRegistros.getValueAt(fila, 0) + "");
        txtNSS2.setText(tblRegistros.getValueAt(fila, 1) + "");

        //SE RECUPERAN LOS DATOS EN ELIMINAR
        txtId1.setText(tblRegistros.getValueAt(fila, 0) + "");
        txtNSS1.setText(tblRegistros.getValueAt(fila, 1) + "");
        nombreSeparado = separarEnPalabras((String) tblRegistros.getValueAt(fila, 2));

        //SE RECUPERA EL NOMBRE Y LOS DEMAS DATOS EN EDITAR
        txtNombre2.setText(nombreSeparado.get(0));
        txtApellidoPaterno2.setText(nombreSeparado.get(1));
        txtApellidoMaterno2.setText(nombreSeparado.get(2));
        txtEdad2.setText(tblRegistros.getValueAt(fila, 3) + "");
        txtAltura2.setText(tblRegistros.getValueAt(fila, 4) + "");

        //SE RECUPERA EL NOMBRE Y LOS DEMAS DATOS EN ELIMINAR
        txtNombre1.setText(nombreSeparado.get(0));
        txtApellidoPaterno1.setText(nombreSeparado.get(1));
        txtApellidoMaterno1.setText(nombreSeparado.get(2));
        txtEdad1.setText(tblRegistros.getValueAt(fila, 3) + "");
        txtAltura1.setText(tblRegistros.getValueAt(fila, 4) + "");

    }//GEN-LAST:event_tblRegistrosMouseClicked
    public void limpiarInsertar() {
        txtNombre.setText("Ingrese 1 nombre");
        txtApellidoPaterno.setText("Ingrese el apellido paterno");
        txtApellidoMaterno.setText("Ingrese el apellido paterno");
        txtNSS.setText("Ingrese NSS");
        txtEdad.setText("Ingrese la edad");
        txtAltura.setText("Ingrese altura");

    }

    public void limpiarEliminar() {
        txtNombre1.setText("Ingrese 1 nombre");
        txtApellidoPaterno1.setText("Ingrese el apellido paterno");
        txtApellidoMaterno1.setText("Ingrese el apellido paterno");
        txtNSS1.setText("Ingrese NSS");
        txtEdad1.setText("Ingrese la edad");
        txtAltura1.setText("Ingrese altura");
        btnRegresar.setEnabled(true);
        insertar(true);
    }

    public void limpiarEditar() {
        txtNombre2.setText("Ingrese 1 nombre");
        txtApellidoPaterno2.setText("Ingrese el apellido paterno");
        txtApellidoMaterno2.setText("Ingrese el apellido paterno");
        txtNSS2.setText("Ingrese NSS");
        txtEdad2.setText("Ingrese la edad");
        txtAltura2.setText("Ingrese altura");
        btnRegresar.setEnabled(true);
        insertar(true);
    }
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            MetodosPaciente metodos = new PacienteImplementacion();
            String nombreCompleto = txtNombre.getText() + " "
                    + txtApellidoPaterno.getText() + " "
                    + txtApellidoMaterno.getText();
            Paciente paciente = new Paciente(Integer.parseInt(txtId.getText()),
                    Integer.parseInt(txtNSS.getText()),
                    nombreCompleto,
                    Integer.parseInt(txtEdad.getText()),
                    Float.valueOf(txtAltura.getText()));

            JOptionPane.showMessageDialog(rootPane,
                    "Se ha registrado " + metodos.registrarPaciente(paciente) + " satisfactoriamente",
                    "Registro realizado de manera exitosa",
                    JOptionPane.INFORMATION_MESSAGE);
            listarRegistros();
            limpiarInsertar();
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(rootPane,
                    "Error al convertir los datos\n"
                    + "Se han ingresado datos invalidos para los datos numericos (edad, altura, nss)\n"
                    + "Favor de verificar detenidamente.\n"
                    + "Error: " + err.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(InterfazPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, """
                                                   Al cambiar de funcion se perderan los cambios de la funcion actual
                                                   Esta usted seguro de querer proceder?""", "Confirmación de eliminacion",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpiarInsertar();
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        // TODO add your handling code here:
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtApellidoPaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoPaternoFocusGained
        // TODO add your handling code here:
        txtApellidoPaterno.setText("");
    }//GEN-LAST:event_txtApellidoPaternoFocusGained

    private void txtApellidoMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoMaternoFocusGained
        // TODO add your handling code here:
        txtApellidoMaterno.setText("");
    }//GEN-LAST:event_txtApellidoMaternoFocusGained

    private void txtEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadFocusGained
        // TODO add your handling code here:
        txtEdad.setText("");
    }//GEN-LAST:event_txtEdadFocusGained

    private void txtAlturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlturaFocusGained
        // TODO add your handling code here:
        txtAltura.setText("");
    }//GEN-LAST:event_txtAlturaFocusGained

    private void txtNSSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNSSFocusGained
        // TODO add your handling code here:
        txtNSS.setText("");
    }//GEN-LAST:event_txtNSSFocusGained

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, """
                                                   Al cambiar de funcion se perderan los cambios de la funcion actual
                                                   Esta usted seguro de querer proceder?""", "Confirmación de eliminacion",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpiarEditar();
            tblRegistros.clearSelection();
            tbdFunciones.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btnBorrar2ActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, """
                                                   Al cambiar de funcion se perderan los cambios de la funcion actual
                                                   Esta usted seguro de querer proceder?""", "Confirmación de eliminacion",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpiarEliminar();
            tblRegistros.clearSelection();
            tbdFunciones.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        MetodosPaciente metodos = new PacienteImplementacion();
        String nombreCompleto = txtNombre2.getText() + " "
                + txtApellidoPaterno2.getText() + " "
                + txtApellidoMaterno2.getText();
        Paciente paciente = new Paciente(Integer.parseInt(txtId2.getText()),
                Integer.parseInt(txtNSS2.getText()),
                nombreCompleto,
                Integer.parseInt(txtEdad2.getText()),
                Float.valueOf(txtAltura2.getText()));
        try {

            JOptionPane.showMessageDialog(rootPane,
                    "Se ha actualizado " + metodos.actualizarPaciente(paciente) + " satisfactoriamente",
                    "Registro realizado de manera exitosa",
                    JOptionPane.INFORMATION_MESSAGE);
            listarRegistros();
            limpiarEditar();
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(rootPane,
                    "Error al convertir los datos\n"
                    + "Se han ingresado datos invalidos para los datos numericos (edad, altura, nss)\n"
                    + "Favor de verificar detenidamente.\n"
                    + "Error: " + err.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(InterfazPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here
        if (JOptionPane.showConfirmDialog(rootPane, "Desea eliminar el paciente?\n"
                + "Esta accion no se puede deshacer...",
                "Confirmar eliminacion",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            MetodosPaciente metodos = new PacienteImplementacion();
            try {
                if (metodos.eliminarPaciente(Integer.parseInt(txtId1.getText())) != -1) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Se ha eliminado de manera satisfactoria",
                            "Eliminación satisfactoria",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                    limpiarEliminar();
                    listarRegistros();
                }
            } catch (Exception err) {
                JOptionPane.showMessageDialog(rootPane,
                        "Ha ocurrido un error al eliminar\n"
                        + "Error: " + err.getMessage());
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        try{
            Home inicio = new Home();
            inicio.setVisible(true);
            // Cerrar la ventana
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrió un error",
                "Error",0);

        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    public ArrayList<String> separarEnPalabras(String texto) {
        // Usamos el método split para dividir el string en palabras usando espacios en blanco como delimitador
        String[] palabrasArray = texto.split("\\s+");

        // El array se convierte en ArrayList para trabajar con él más facilmente
        ArrayList<String> palabrasList = new ArrayList<>(Arrays.asList(palabrasArray));

        return palabrasList;
    }

    public void insertar(boolean activacion) {
        txtId.setEnabled(activacion);
        txtNombre.setEnabled(activacion);
        txtApellidoPaterno.setEnabled(activacion);
        txtApellidoMaterno.setEnabled(activacion);
        txtNSS.setEnabled(activacion);
        txtEdad.setEnabled(activacion);
        txtAltura.setEnabled(activacion);
        btnRegistrar.setEnabled(activacion);
        btnBorrar.setEnabled(activacion);

    }

    public void eliminar(boolean activacion) {
        btnEliminar.setEnabled(activacion);
        btnBorrar1.setEnabled(activacion);
        btnRegresar.setEnabled(!activacion);
    }

    public void editar(boolean activacion) {
        txtId2.setEnabled(activacion);
        txtNombre2.setEnabled(activacion);
        txtApellidoPaterno2.setEnabled(activacion);
        txtApellidoMaterno2.setEnabled(activacion);
        txtNSS2.setEnabled(activacion);
        txtEdad2.setEnabled(activacion);
        txtAltura2.setEnabled(activacion);
        btnGuardar.setEnabled(activacion);
        btnBorrar2.setEnabled(activacion);
        btnRegresar.setEnabled(!activacion);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazPaciente().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(InterfazPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void listarRegistros() throws Exception {
        MetodosPaciente metodos = new PacienteImplementacion();
        tblRegistros.setModel(metodos.recuperarPacientes(
                cmbFiltro.getSelectedIndex(),
                txtCriterio.getText(),
                cmbOrden.getSelectedIndex()));
        txtId.setText(metodos.recuperarUltimo() + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JComboBox<String> cmbOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tbdFunciones;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAltura1;
    private javax.swing.JTextField txtAltura2;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoMaterno1;
    private javax.swing.JTextField txtApellidoMaterno2;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtApellidoPaterno1;
    private javax.swing.JTextField txtApellidoPaterno2;
    private javax.swing.JTextField txtCriterio;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdad1;
    private javax.swing.JTextField txtEdad2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtNSS;
    private javax.swing.JTextField txtNSS1;
    private javax.swing.JTextField txtNSS2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables
}
